version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SQL123$456"
    ports:
      - "1433:1433"
  api:
    image: conduitapi:latest
    build:
      context: .
      dockerfile: API/Dockerfile
    command: dotnet ef database update
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db